# permissions for end users to view flippers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flipper-viewer-role
rules:
- apiGroups:
  - flipper.dev.io
  resources:
  - flippers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flipper.dev.io
  resources:
  - flippers/status
  verbs:
  - get
