apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrong-label-deployment-2
  namespace: mesh
  labels:
    mesh: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      mesh: "true"
  template:
    metadata:
      labels:
        mesh: "true"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80